[template]
ignore = [
    ".git",
    "README.md"
]

# lib or bin?
[conditional.'crate_type == "lib"']
ignore = [ "src/main.rs" ]

[conditional.'crate_type == "bin"']
ignore = [ "src/lib.rs" ]

# cargo-release?
[placeholders.with_cargo_release]
type = "bool"
prompt = "Use cargo-release for publishing?"
default = false